### ISSUE TITLE
connected components

### ISSUE THREAD

**Issue by peach-lucien** [barahona-research-group/GDR#1]
The current implementation uses the out-dated networkx command for connected_component_subgraphs. This needs updating for users, otherwise it won't work with current networkx package.

**Comment by arnaudon** [comment]
like that? https://github.com/barahona-research-group/GDR/commit/a1799a0f63f04b5f181baec40b9795316d599b33

**Comment by peach-lucien** [comment]
that looks good - does it work? Can you also make the same update for multiscale centrality?

**Comment by arnaudon** [comment]
I didn't try to run it, could you quickly try? If it works, I'll update MSC the same.
